# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hand_controller:
  ros__parameters:
    joints:
      - base_link_to_link1
      - link1_to_link2
      - link2_to_link3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.0  # No time constraint
      base_link_to_link1: {goal: 0.002}  # 0.002 rad goal tolerance
      link1_to_link2: {goal: 0.002}
      link2_to_link3: {goal: 0.002}
gripper_controller:
  ros__parameters:
    joint: link3_to_gripper_link